### ISSUE TITLE
Error: NRT Calculation

### ISSUE THREAD

**Issue by igorleite91** [Clark-Labs/UDef-ARP#10]
I'm trying to calculate the NRT within the application. However, I'm getting the following message:

'an error occurred during processing: arrange: cannot calculate length'

![image](https://github.com/Clark-Labs/UDef-ARP/assets/49123452/70fbd766-cd9a-4610-b3c2-f2210f52d69c)

The error only appears when I request the NRT calculation. If I define NRT value, I do not get any error. 

Could you, please, help me with this issue?

**Comment by agcopenhaver** [comment]
Hi @igorleite91  - can you please provide the gdalinfo outputs for your distance to forest edge raster in the calibration period, your binary deforestation mask for the HRP, and the jurisdictional mask.

**Comment by igorleite91** [comment]
Hi @agcopenhaver! Below is the gdalinfo output for each of the files.

The gdalinfo outputs:

**- Distance to forest edge**
Driver: GTiff/GeoTIFF
Files: dist_t1_crop.tif
Size is 1986, 2324
Coordinate System is:
PROJCS["WGS 84 / UTM zone 22S",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-51],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","32722"]]
Origin = (172452.523800000000000,9362764.789200000500000)
Pixel Size = (29.836149144008065,-29.836149096385562)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  172452.524, 9362764.789)
Lower Left  (  172452.524, 9293425.579)
Upper Right (  231707.116, 9362764.789)
Lower Right (  231707.116, 9293425.579)
Center      (  202079.820, 9328095.184)
Band 1 Block=1986x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=9906.000
  Minimum=0.000, Maximum=9906.000, Mean=-9999.000, StdDev=-9999.000
  NoData Value=nan
  Metadata:
    DESCRIPTION=dist_t1
    STATISTICS_MAXIMUM=9906
    STATISTICS_MEAN=-9999
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=-9999
    

**- binary deforestation mask**
Driver: GTiff/GeoTIFF
Files: desmatamento_t1_t3.tif
Size is 1986, 2324
Coordinate System is:
PROJCS["WGS 84 / UTM zone 22S",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-51],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","32722"]]
Origin = (172452.523800000000000,9362764.789200000500000)
Pixel Size = (29.836149144008065,-29.836149096385562)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  172452.524, 9362764.789)
Lower Left  (  172452.524, 9293425.579)
Upper Right (  231707.116, 9362764.789)
Lower Right (  231707.116, 9293425.579)
Center      (  202079.820, 9328095.184)
Band 1 Block=1986x1 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=1.000
  Minimum=0.000, Maximum=1.000, Mean=-9999.000, StdDev=-9999.000
  NoData Value=nan
  Metadata:
    DESCRIPTION=brasil_coverage_2013
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=-9999
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=-9999
    

**- jurisdictional mask:**
Driver: GTiff/GeoTIFF
Files: jurisdiction.tif
Size is 1986, 2324
Coordinate System is:
PROJCS["WGS 84 / UTM zone 22S",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-51],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","32722"]]
Origin = (172452.523800000000000,9362764.789200000500000)
Pixel Size = (29.836149144008065,-29.836149096385562)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  172452.524, 9362764.789)
Lower Left  (  172452.524, 9293425.579)
Upper Right (  231707.116, 9362764.789)
Lower Right (  231707.116, 9293425.579)
Center      (  202079.820, 9328095.184)
Band 1 Block=1986x1 Type=Float32, ColorInterp=Gray
  Min=1.000 Max=1.000
  Minimum=1.000, Maximum=1.000, Mean=-9999.000, StdDev=-9999.000
  NoData Value=nan
  Metadata:
    DESCRIPTION=layer
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=-9999
    STATISTICS_MINIMUM=1
    STATISTICS_STDDEV=-9999

**Comment by YaoTingYao** [comment]
Hi @igorleite91 

Thanks for providing your data info. I noticed an issue with the jurisdictional mask. Currently, both the maximum and minimum values are set to 1. This may lead to errors when attempting to compute the histogram for the NRT value in line 69: 
https://github.com/Clark-Labs/UDef-ARP/blob/103c0c3a648f8982476c22beb0bfc7c6287ae695/vulnerability_map.py#L69.

For the histogram computation to work correctly, the jurisdictional mask needs to be binary, with values of 0 and 1 only. Adjusting the mask accordingly should help avoid this error.

Please feel free to reach out if you have any questions or issues. Cheers!

**Comment by igorleite91** [comment]
Hi @YaoTingYao

Thank you very much for your very detailed answer. Following your recommendation, I create a jurisdiction mask with values of 0 and 1.  I see that jurisdiction data is used as a mask in line 53. You can see the raster info below. Unfortunately I'm still getting the same error.

I would really appreciate if you could help me once again.

Jurisdiction raster:
Files: jurisdiction_v2.tif
Size is 1986, 2324
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 22S",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 22S",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-51,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",10000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Navigation and medium accuracy spatial referencing."],
        AREA["Between 54┬░W and 48┬░W, southern hemisphere between 80┬░S and equator, onshore and offshore. Brazil. Uruguay."],
        BBOX[-80,-54,0,-48]],
    ID["EPSG",32722]]
Data axis to CRS axis mapping: 1,2
Origin = (172452.523799999995390,9362764.789200000464916)
Pixel Size = (29.836149144008065,-29.836149096385562)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  172452.524, 9362764.789) ( 53d57'25.61"W,  5d45'26.63"S)
Lower Left  (  172452.524, 9293425.579) ( 53d57'37.93"W,  6d23' 1.74"S)
Upper Right (  231707.116, 9362764.789) ( 53d25'21.08"W,  5d45'35.71"S)
Lower Right (  231707.116, 9293425.579) ( 53d25'31.17"W,  6d23'11.83"S)
Center      (  202079.820, 9328095.184) ( 53d41'28.91"W,  6d 4'19.22"S)
Band 1 Block=1986x1 Type=Float32, ColorInterp=Gray
  Description = layer
  Min=0.000 Max=1.000
  Minimum=0.000, Maximum=1.000, Mean=-9999.000, StdDev=-9999.000
  NoData Value=nan
  Metadata:
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=-9999
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=-9999

**Comment by agcopenhaver** [comment]
Hi @igorleite91 are you able to attach the data in question so we can give it a look?

**Comment by igorleite91** [comment]
Hey @agcopenhaver,

In the .zip file are the .tif data that I am trying to use for the NRT calculation:

[data.zip](https://github.com/Clark-Labs/UDef-ARP/files/14532806/data.zip)

**Comment by tawoodard** [comment]
I just took a peek at the data.  The data in deforestation_mask.tif are continuous data ranging from 0-1.  It's supposed to be a binary (boolean) file of only 0's or 1's.

**Comment by igorleite91** [comment]
Thank you very much for the observation.
I was using R programming to create the input data, and even though I checked the raster values, the compression option that I was using to save the .tif files somehow converted them to float. I am still trying to understand it properly. However, by defining the datatype while saving the raster, I was able to create them as binary.

Fortunately, I was able to move forward in the application. However, I am now facing another issue. In the second step of the prediction phase of the testing stage, I cannot obtain the second output (adjusted predicted CNF density map). I receive the first output (modeling region map in the CNF), but not the second. I have attached the data just in case you would like to review it. I really appreciate all the help so far.

P.S.: Do not mind the results of the fitting tests. At the moment, I am just trying to understand the methodology.

The image below shows the input data

![image](https://github.com/Clark-Labs/UDef-ARP/assets/49123452/b1d61750-41ff-4a89-8178-7558c2478212)
[data.zip](https://github.com/Clark-Labs/UDef-ARP/files/14565137/data.zip)

**Comment by agcopenhaver** [comment]
Hi @igorleite91, I think you may just need to double-check your data and all steps leading to this point. I'm looking through your relative frequency table and it has negative values in the ID and other values that shouldn't be in there based on your admin regions file that you've shared.

**Comment by agcopenhaver** [comment]
@igorleite91 I'm going to close this issue as your issue with the NRT is solved. If you continue to have issues, please feel free to open a new one

**Comment by igorleite91** [comment]
Hi.
Thank you for all the help. I manage to reproduce all workflow using my testing data. 
However, I still have one question left. In another issue (that is closed), it is mentioned that the deforestion estimated in the HRP should be used 
as quantity adjusment, if I understood it correctly. But, on page 20, it is mentioned that the deforestation in the confirmation period should be used
as quantity adjustment. I am not sure if I understood this divergent points. Could you, please, clarify it? 

Thanks in advance.

**Comment by agcopenhaver** [comment]
It depends on what stage you're at what you will use. For testing, use data from the relevant period to adjust - so that would be from confirmation period.

In the application stage, you would use the data from the HRP or activity data estimates.

**Comment by igorleite91** [comment]
Great. Thank you very much!!
