### ISSUE TITLE
HRP, FCBM, and AD used for the example in the VT0007

### ISSUE THREAD

**Issue by igorfuture** [Clark-Labs/UDef-ARP#11]
Hello team, congratulations on the work.

We are reproducing the analyzes carried out for the state of Pará, Brazil, which was used as an example in VT0007.

However, it is not clear which HRP and source of land use input data are used in the analysis and determination of FCBM and AD.

Can this be provided/informed for testing and comparative analysis purposes?

Thanks

**Comment by agcopenhaver** [comment]
Hi @igorfuture  - could you please submit this question to forestcarbon@verra.org. Thanks
