### ISSUE TITLE
Clarification about the about Expected Jurisdictional Activity (ha) input

### ISSUE THREAD

**Issue by JohnKilbride** [Clark-Labs/UDef-ARP#12]
Hello, 

I think I'm pretty close to having my workflow for running the new VT0007 tool worked out. 

One stumbling block is how to interpret an input for the Validity Period Allocated Risk Mapping step. The input is the "Expected Jurisdictional Activity (ha)" field in the tools. The help indicates that this is "This is a value, in hectares, for the expected deforestation activity in the VP as determined from sampling."

Is this value generated in one of the previous steps? Or, if we are working with wall-to-wall maps of deforestation, should we just sum the deforestation that occurred throughout the historical reference period and input that as the Expected Jurisdictional Activity? 

Thank you!

**Comment by agcopenhaver** [comment]
@JohnKilbride, it's the latter. When Verra uses this tool for allocation, that value will come from our jurisdictional deforestation estimates based on the visual interpretation of samples, not from the wall-to-wall maps. Basically, we're adjusting the quantity of the predicted deforestation per pixel to what was estimated in the HRP. 

So for the testing stage, exactly, just sum deforestation from the wall-to-wall maps during the relevant period. But you could also use a value from a FREL or similar if you had that available.

**Comment by JohnKilbride** [comment]
Excellent, that is super helpful!

And hey -- I've got my first, nice lookin' risk map! Thanks for the assistance!
