### ISSUE TITLE
[BUG] Assessment Grid Removing Valid Cells

### ISSUE THREAD

**Issue by agcopenhaver** [Clark-Labs/UDef-ARP#3]
Hi there - 

I believe I've found a pretty straightforward bug in the code referenced [here](https://github.com/Clark-Labs/UDef-ARP/blob/c03d3bf07933640d2c556bb1a24bd656ba748d3b/model_evaluation.py#L256C1-L277C39)

It appears that due how the edge / irregular grid cells are removed by selecting only polys that are equal to the maximum area of a grid cell, that we are introducing some precision issues, which removes what I'd say are valid polygons that are only like 0.000004 percent different from the maximum value (see result in map below). 

![image](https://github.com/Clark-Labs/UDef-ARP/assets/15128391/008acc04-ce42-47e9-8a3a-047d3950475e)

The attached table also shows what I believe is the source of the issue. - with the unhighlighted cells being retained because they are equivalent to the max, but the blue highlighted cells being removed because of their extremely minute differences.
![image](https://github.com/Clark-Labs/UDef-ARP/assets/15128391/77567c78-c9b6-4903-9b08-7a34dd142d60)

In the map below, the yellow cells would be the ones that should be removed, with the pink being retained:

![image](https://github.com/Clark-Labs/UDef-ARP/assets/15128391/cd8390af-a48d-4bfa-8a07-43c5635a1272)

I see a couple of ways forward with this issue. The first is a purely geospatial approach, which modifies the overlay operation:

` thiessen_gdf = gpd.overlay(df1=voronois, df2=polydf, how="intersection", keep_geom_type=False)` [source here](https://github.com/Clark-Labs/UDef-ARP/blob/c03d3bf07933640d2c556bb1a24bd656ba748d3b/model_evaluation.py#L257)

to a "within" instead of a intersection, e.g:
`thiessen_gdf = gpd.sjoin(voronois, polydf, how="inner", predicate="within")`, which would select only grid cells completely within the binary mask area. This yields the green areas below:

![image](https://github.com/Clark-Labs/UDef-ARP/assets/15128391/9737ee0e-d2af-4be7-83e8-08ec755a21b7)

However, I find that this approach, while it solves the problem identified here and follows the rules we've put forth in the tool is perhaps a bit too ungenerous in defining an edge cell. By that I mean, we're removing what I think are conceptually similar cells that are just barely not completely contained within the binary mask area, like the ones shown below.
 
![image](https://github.com/Clark-Labs/UDef-ARP/assets/15128391/92530f17-aad5-46d9-b8fb-34b717ea7aaf)

Therefore, I'd like to propose something like the cell size needing to exceed a set threshold of maximum cell size, e.g. after intersection, the cell needs to be at least 99% of the max cell size:
```
def remove_edge_cells(full_voronoi_grid: GeoDataFrame, area_mask: GeoDataFrame,  
       area_percentile_threshold: float) -> GeoDataFrame:
       thiessen_gdf = gpd.overlay(full_voronoi_grid, area_mask, how="intersection")
       # get area of each polygon
       thiessen_gdf["area"] = thiessen_gdf.area

       max_area = thiessen_gdf["area"].max()
       # using the area, calculate size of cell compared to max
       thiessen_gdf["percentcell"] = thiessen_gdf["area"] / max_area

       # select cells with more than thresh% of their area within the mask
       thiessen_gdf = thiessen_gdf[thiessen_gdf["percentcell"] > area_percentile_threshold]
    
       return thiessen_gdf
```
which would give us those barely different cells:
![image](https://github.com/Clark-Labs/UDef-ARP/assets/15128391/c257c570-69fc-4847-83c5-934f064fb545)

I'm happy to submit a PR to do either, as I've already written the fixes. Let me know what you think.

**Comment by YaoTingYao** [comment]
Hi @agcopenhaver ,

Thank you immensely for bringing this bug to our attention. The detailed evidence you've shared clearly demonstrates the necessity of refining our precision handling. You've outlined two viable approaches, and the idea of adjusting selection criteria to include cells at least 99% maximum cell size is particularly compelling.

Your thoughtful analysis is deeply appreciated. We are more than happy to review a pull request from you incorporating this solution. Please feel free to submit a PR at your convenience. Thanks for your contributions. Cheers!

**Comment by agcopenhaver** [comment]
Hi Yao-Ting. I submitted a PR using my fork, as I don't think I'm in the access group that can modify the repo.

**Comment by YaoTingYao** [comment]
Hi @agcopenhaver, thank you for submitting your PR! We're happy to have you as a collaborator in the repository. Regarding your suggestion about the 99% maximum cell size function, we find it to be an intriguing idea. Would you be interested in incorporating this feature into your current PR as well or would you prefer that we integrate your proposal into the script on our end? We believe this addition could significantly enhance the project's value. Thanks again for your contribution. Looking forward to your thoughts. Cheers!

**Comment by agcopenhaver** [comment]
Hi @YaoTingYao  - thanks for adding me as a collaborator. I'll add in the maximum cell size function in a separate PR.

For now, the actual VT0007 tool on which this is all based, which is in review, does not reference the 99% function. 

I need to discuss that with my team before we alter VT0007 so close to release.
