### ISSUE TITLE
[Documentation] Verra VT0007 renamed

### ISSUE THREAD

**Issue by agcopenhaver** [Clark-Labs/UDef-ARP#5]
Hi - a quick update from Verra, but we've had to modify the tool name given some internal requirements for naming conventions, and it's now named the Unplanned Deforestation Allocation (UDef-A).

I'm not proposing we alter the name of the repo as it's distinct enough from the tool itself, but would you mind if I updated referenced to VT0007 UDef-AT in the documentation to match the change?

Thanks.

**Comment by YaoTingYao** [comment]
Hi @agcopenhaver 
Apologies for the delayed response. Thank you for providing the update regarding how you view the repository name and documentation. I have shared with our team, and we are pleased to move forward with it. Cheers!
